export const mockCategories = [
  {
    id: '1',
    name: 'Concerts',
    slug: 'concerts',
    description: 'Concerts et spectacles musicaux',
    icon: 'music',
    is_active: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Conférences',
    slug: 'conferences',
    description: 'Événements professionnels et conférences',
    icon: 'briefcase',
    is_active: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Sports',
    slug: 'sports',
    description: 'Événements sportifs',
    icon: 'trophy',
    is_active: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Festivals',
    slug: 'festivals',
    description: 'Festivals culturels et artistiques',
    icon: 'star',
    is_active: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockOrganizers = [
  {
    id: '1',
    user_id: 'org-user-1',
    organization_name: 'EventPro Sénégal',
    organization_type: 'company',
    verification_status: 'verified',
    contact_email: 'contact@eventpro.sn',
    contact_phone: '+221771234567',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'org-user-2',
    organization_name: 'Culture Dakar',
    organization_type: 'association',
    verification_status: 'verified',
    contact_email: 'info@culturedakar.sn',
    contact_phone: '+221775556789',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockTicketTypes = [
  {
    id: '1',
    event_id: '1',
    name: 'VIP',
    description: 'Accès exclusif avec privilèges',
    price: 50000,
    currency: 'XOF',
    quantity_total: 100,
    quantity_sold: 45,
    quantity_available: 55,
    is_active: true,
    sales_start_date: new Date().toISOString(),
    sales_end_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    event_id: '1',
    name: 'Standard',
    description: 'Accès standard',
    price: 25000,
    currency: 'XOF',
    quantity_total: 500,
    quantity_sold: 320,
    quantity_available: 180,
    is_active: true,
    sales_start_date: new Date().toISOString(),
    sales_end_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    event_id: '2',
    name: 'Pass Journée',
    description: 'Accès pour une journée',
    price: 15000,
    currency: 'XOF',
    quantity_total: 200,
    quantity_sold: 78,
    quantity_available: 122,
    is_active: true,
    sales_start_date: new Date().toISOString(),
    sales_end_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockEvents = [
  {
    id: '1',
    organizer_id: '1',
    category_id: '1',
    title: 'Youssou N\'Dour Live Concert',
    slug: 'youssou-ndour-live-concert',
    description: 'Concert exceptionnel du légendaire Youssou N\'Dour au Grand Théâtre de Dakar',
    long_description: 'Rejoignez-nous pour une soirée inoubliable avec la légende sénégalaise Youssou N\'Dour. Un spectacle unique mêlant mbalax traditionnel et sonorités modernes.',
    event_image_url: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
    venue_name: 'Grand Théâtre National',
    venue_address: 'Place du Souvenir Africain, Dakar',
    venue_city: 'Dakar',
    venue_country: 'Sénégal',
    venue_latitude: 14.6928,
    venue_longitude: -17.4467,
    start_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    timezone: 'Africa/Dakar',
    status: 'published',
    is_featured: true,
    max_attendees: 600,
    min_age: 0,
    tags: ['concert', 'mbalax', 'musique'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
    organizer: mockOrganizers[0],
    ticket_types: [mockTicketTypes[0], mockTicketTypes[1]],
  },
  {
    id: '2',
    organizer_id: '2',
    category_id: '2',
    title: 'Tech Summit Dakar 2025',
    slug: 'tech-summit-dakar-2025',
    description: 'La plus grande conférence tech d\'Afrique de l\'Ouest',
    long_description: 'Rencontrez les leaders de la tech africaine, découvrez les innovations et connectez-vous avec des investisseurs internationaux.',
    event_image_url: 'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg',
    venue_name: 'King Fahd Palace Hotel',
    venue_address: 'Route de la Corniche Ouest, Almadies',
    venue_city: 'Dakar',
    venue_country: 'Sénégal',
    venue_latitude: 14.7167,
    venue_longitude: -17.4834,
    start_date: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: 'Africa/Dakar',
    status: 'published',
    is_featured: true,
    max_attendees: 200,
    min_age: 18,
    tags: ['tech', 'innovation', 'business'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
    organizer: mockOrganizers[1],
    ticket_types: [mockTicketTypes[2]],
  },
  {
    id: '3',
    organizer_id: '1',
    category_id: '4',
    title: 'Festival Saint-Louis Jazz',
    slug: 'festival-saint-louis-jazz',
    description: 'Festival international de jazz à Saint-Louis',
    long_description: 'Le festival de jazz le plus ancien d\'Afrique vous invite pour une semaine de concerts exceptionnels dans la ville historique de Saint-Louis.',
    event_image_url: 'https://images.pexels.com/photos/1916824/pexels-photo-1916824.jpeg',
    venue_name: 'Place Faidherbe',
    venue_address: 'Île de Saint-Louis',
    venue_city: 'Saint-Louis',
    venue_country: 'Sénégal',
    venue_latitude: 16.0180,
    venue_longitude: -16.4895,
    start_date: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: new Date(Date.now() + 47 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: 'Africa/Dakar',
    status: 'published',
    is_featured: false,
    max_attendees: 1000,
    min_age: 0,
    tags: ['jazz', 'festival', 'musique'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[3],
    organizer: mockOrganizers[0],
    ticket_types: [],
  },
  {
    id: '4',
    organizer_id: '2',
    category_id: '3',
    title: 'Marathon de Dakar',
    slug: 'marathon-de-dakar',
    description: 'Course internationale de marathon à travers Dakar',
    long_description: 'Participez au Marathon de Dakar, une course spectaculaire longeant la corniche et traversant les quartiers emblématiques de la capitale sénégalaise.',
    event_image_url: 'https://images.pexels.com/photos/2524739/pexels-photo-2524739.jpeg',
    venue_name: 'Corniche de Dakar',
    venue_address: 'Point de départ: Monument de la Renaissance',
    venue_city: 'Dakar',
    venue_country: 'Sénégal',
    venue_latitude: 14.7167,
    venue_longitude: -17.4677,
    start_date: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
    timezone: 'Africa/Dakar',
    status: 'published',
    is_featured: true,
    max_attendees: 5000,
    min_age: 16,
    tags: ['sport', 'marathon', 'course'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[2],
    organizer: mockOrganizers[1],
    ticket_types: [],
  },
];

export const mockBookings = [
  {
    id: '1',
    event_id: '1',
    user_id: 'user-123',
    ticket_type_id: '1',
    quantity: 2,
    unit_price: 50000,
    total_amount: 100000,
    currency: 'XOF',
    booking_status: 'confirmed',
    payment_status: 'paid',
    payment_method: 'orange_money',
    booking_reference: 'EP-20250115-001',
    qr_code_data: 'EP-20250115-001-VIP-2',
    check_in_status: 'pending',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    event_id: '1',
    user_id: 'user-456',
    ticket_type_id: '2',
    quantity: 4,
    unit_price: 25000,
    total_amount: 100000,
    currency: 'XOF',
    booking_status: 'confirmed',
    payment_status: 'paid',
    payment_method: 'wave',
    booking_reference: 'EP-20250116-002',
    qr_code_data: 'EP-20250116-002-STD-4',
    check_in_status: 'pending',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockStats = {
  totalRevenue: 15750000,
  pendingPayouts: 2500000,
  totalBookings: 1247,
  activeEvents: 12,
  upcomingEvents: 8,
  pastEvents: 24,
  totalTicketsSold: 3456,
  revenueByMonth: [
    { month: 'Jan', revenue: 2500000 },
    { month: 'Fév', revenue: 3200000 },
    { month: 'Mar', revenue: 2800000 },
    { month: 'Avr', revenue: 3500000 },
    { month: 'Mai', revenue: 3750000 },
  ],
};

export const mockPayouts = [
  {
    id: '1',
    organizer_id: '1',
    amount: 850000,
    currency: 'XOF',
    status: 'pending',
    payment_method: 'bank_transfer',
    requested_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    organizer_id: '2',
    amount: 1650000,
    currency: 'XOF',
    status: 'pending',
    payment_method: 'orange_money',
    requested_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockUsers = {
  admin: {
    id: 'Tnq8Isi0fATmidMwEuVrw1SAJkI3',
    email: 'admin@evenpass.sn',
    role: 'admin',
    full_name: 'Admin EvenPass',
    permissions: ['finance', 'ops_manager', 'scanner', 'all_access']
  },
  organizer: {
    id: 'org-user-1',
    email: 'organisateur@evenpass.sn',
    role: 'organizer',
    full_name: 'Organisateur Test',
    organization_id: '1'
  }
};

export const mockFinanceStats = {
  totalRevenue: 45680000,
  pendingPayouts: 8750000,
  completedPayouts: 36930000,
  totalTransactions: 2847,
  revenueThisMonth: 12400000,
  revenueLastMonth: 9850000,
  averageTicketPrice: 16050,
  topEvents: [
    { event_name: 'Youssou N\'Dour Live Concert', revenue: 18250000, tickets_sold: 365 },
    { event_name: 'Tech Summit Dakar 2025', revenue: 11700000, tickets_sold: 780 },
    { event_name: 'Marathon de Dakar', revenue: 8430000, tickets_sold: 526 },
  ],
  revenueByPaymentMethod: [
    { method: 'Orange Money', amount: 22340000, percentage: 48.9 },
    { method: 'Wave', amount: 18120000, percentage: 39.7 },
    { method: 'Carte Bancaire', amount: 5220000, percentage: 11.4 },
  ]
};

export const mockOpsStats = {
  totalEvents: 42,
  activeEvents: 12,
  draftEvents: 5,
  completedEvents: 25,
  totalOrganizers: 18,
  verifiedOrganizers: 15,
  pendingVerifications: 3,
  totalTicketsSold: 8934,
  totalCapacity: 15670,
  occupancyRate: 57,
  recentActivities: [
    { action: 'Nouvel événement créé', organizer: 'EventPro Sénégal', event: 'Concert Wally Seck', time: '2h' },
    { action: 'Organisateur vérifié', organizer: 'Culture Dakar', time: '5h' },
    { action: 'Événement publié', organizer: 'Sports Events', event: 'Match de Basketball', time: '1j' },
  ]
};

export const mockScanStats = {
  totalScans: 1247,
  validScans: 1189,
  invalidScans: 58,
  duplicateScans: 12,
  scansToday: 234,
  scansThisWeek: 892,
  peakScanTime: '19h00 - 20h00',
  averageScanTime: '2.3s',
  recentScans: [
    {
      ticket_reference: 'EP-20250115-001',
      event: 'Youssou N\'Dour Concert',
      type: 'VIP',
      status: 'valid',
      scanned_at: new Date(Date.now() - 2 * 60 * 1000).toISOString()
    },
    {
      ticket_reference: 'EP-20250116-045',
      event: 'Tech Summit Dakar',
      type: 'Standard',
      status: 'valid',
      scanned_at: new Date(Date.now() - 5 * 60 * 1000).toISOString()
    },
    {
      ticket_reference: 'EP-20250114-089',
      event: 'Marathon de Dakar',
      type: 'Participant',
      status: 'duplicate',
      scanned_at: new Date(Date.now() - 8 * 60 * 1000).toISOString()
    },
  ]
};
