import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { FirebaseAuthProvider, useAuth } from './context/FirebaseAuthContext';
import { ThemeProvider } from './context/ThemeContext';
import { DemDemThemeProvider } from './contexts/DemDemThemeContext';
import ThemeWrapper from './components/ThemeWrapper';

// Imports corrigés (sans accolades pour les exports par défaut)
import DemDemLandingPage from './pages/DemDemLandingPage';
import RootLandingPage from './pages/RootLandingPage';
import VoyageLandingPage from './pages/VoyageLandingPage';
import EventLandingPageNew from './pages/EventLandingPageNew';
import HomePageNew from './pages/HomePageNew';
import EventDetailPage from './pages/EventDetailPage';
import SuccessPage from './pages/SuccessPage';
import ErrorPage from './pages/ErrorPage';
import HowItWorksPage from './pages/HowItWorksPage';
import ForOrganizersPage from './pages/ForOrganizersPage';
import HelpPage from './pages/HelpPage';
import TermsPage from './pages/TermsPage';
import OrganizerDashboardPage from './pages/OrganizerDashboardPage';
import OrganizerSignupPage from './pages/OrganizerSignupPage';
import OrganizerLoginPage from './pages/OrganizerLoginPage';
import PendingVerificationPage from './pages/PendingVerificationPage';
import AdminFinancePage from './pages/AdminFinancePage';
import AdminFinanceLoginPage from './pages/AdminFinanceLoginPage';
import OpsManagerPage from './pages/OpsManagerPageNew';
import OpsManagerLoginPage from './pages/OpsManagerLoginPage';
import EPscanLoginPage from './pages/EPscanLoginPage';
import PassLandingPage from './pages/pass/PassLandingPage';
import PassServicesPage from './pages/pass/PassServicesPage';
import LMDGBookingPage from './pages/pass/LMDGBookingPage';
import COSAMABookingPage from './pages/pass/COSAMABookingPage';
import InterregionalBookingPage from './pages/pass/InterregionalBookingPage';
import PaymentSuccessPage from './pages/pass/PaymentSuccessPage';
import PaymentErrorPage from './pages/pass/PaymentErrorPage';
import SubscriptionPage from './pages/SubscriptionPage';
import WalletPage from './pages/WalletPage';
import AdminTransversalDashboard from './pages/AdminTransversalDashboard';
import SecurityManifestPage from './pages/SecurityManifestPage';
import CommandantDashboard from './pages/CommandantDashboard';
import BoardingDashboard from './pages/BoardingDashboard';
import CommercialDashboard from './pages/CommercialDashboard';
import BoardingLoginPage from './pages/pass/BoardingLoginPage';
import CommandantLoginPage from './pages/pass/CommandantLoginPage';
