name: Force Deploy DemDem
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install & Build
        # CI=false empêche le build de s'arrêter sur des avertissements
        run: |
          npm install --legacy-peer-deps
          CI=false npm run build

      - name: Firebase Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # ATTENTION : Nom exact du secret vérifié dans tes paramètres
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVENPASSSENEGAL }}'
          channelId: live
          projectId: evenpasssenegal
